### ISSUE TITLE
Will not import transactions from .qmtf file (renamed to .qif)

### ISSUE THREAD

**Issue by wkcwells** [isaacharrisholt/quiffen#1]
Hello, Quiffen looks great!  I have a large Quicken for Mac file exported as .qmtf.  When I parse this into quiffen, I get all of the accounts, but no transactions.

**Comment by wkcwells** [comment]
Upon debugging, the transaction parsing isn't working for various differences in the file I exported from what Quiffen is expecting.  I'll collect the differences and get back to you.  Thanks.

**Comment by isaacharrisholt** [comment]
Awesome, thanks. I'll try to expand support for QMTF files once you do!

**Comment by isaacharrisholt** [comment]
Hi @wkcwells, did you ever have any luck with this? I'd like to add support for QMTF files if I can

**Comment by isaacharrisholt** [comment]
I'm closing this issue. Please feel free to re-open it if you have files you can provide.
