### ISSUE TITLE
Parse fails on Property & Debt Account 'House'

### ISSUE THREAD

**Issue by rand-num** [isaacharrisholt/quiffen#11]
I am doing a simple parse of a QIF file hat includes Property & Debt accounts as well as Banking accounts. With this setup I get the following: 

```
~/quicken/.venv/lib/python3.8/site-packages/quiffen/core/transactions.py in from_list(cls, lst, day_first, line_number)
    532             elif line_code == 'N':
    533                 if not splits:
--> 534                     kwargs['check_number'] = int(field_info)
    535                 else:
    536                     current_split.check_number = int(field_info)

ValueError: invalid literal for int() with base 10: 'House'
```

Do I need to exclude Property & Debt accounts?

**Comment by rand-num** [comment]
By the way, I was looking through the QIF file, and there are two places where the string 'NHouse' appears...

At the top of the QIF file there is what appears to be a list of accounts in a section that looks like this...

```
!Option:AutoSwitch
!Account
NACCOUNT1
TBank
^

...other accounts listed here

NHouse
TOth A
^

...other accounts listed here
```
And then further down in the file we have:
```
!Type:Oth A
!Account
NHouse
TOth A
^
!Type:Oth A
D6/30'21
U1.00
T1.00
CX
PZillow Market Adjustment
L[House]/market_adjustment
^
```

Those are the only two places 'NHouse' appears in the QIF file. Thanks in advance for your help!

**Comment by isaacharrisholt** [comment]
Apologies for taking so long to get back to you. Quiffen does not currently support Property & Debt accounts.
