### ISSUE TITLE
Populate category hierarchy for transactions with multiple "L" lines.

### ISSUE THREAD

**Issue by adrianratnapala** [isaacharrisholt/quiffen#12]
My bank tags each transcation with a "category" and "subcategory", and writes both out as an "L" line in `.qif` format. Does quiffen handle this scenario? And if not, would it be feasible to handle it?

For example a transaction might look like:
```
D21/12/2021
T-1234.56
PDescription Describes the Describable
LRepitle
LLizzard
^
```

So I would expect this to have a category like "Reptile/Lizard" that is auto-inserted into the category hierarchy.  Or if it doesn't auto-create categories, maybe I have to pre-poulate the category hierarchy? In which case  can I get an error result when the input data contains an unexpected category?

**Comment by isaacharrisholt** [comment]
My apologies for the slow response on this. The code does auto-create categories. At the moment, it does not check for multiple categories like this, as the official QIF standard is to separate subcategories by semi-colons. However, this is certainly something that is doable.

**Comment by isaacharrisholt** [comment]
This feature has been added as of Quiffen 1.2.0.
