### ISSUE TITLE
Update minimal Python version

### ISSUE THREAD

**Issue by kapitan-iglu** [isaacharrisholt/quiffen#17]
I looked for module to generate QIF files which is compatible with old Python 3.4. I found `quiffen` and was happy because it supports all versions of Python3 (`python_requires='>=3'`). But reality was a little bit different:

1. `quiffen` uses `f'strings` which were added in Python 3.6...
2. Presence of pandas package is tested agains `ModuleNotFoundError` exception which was introduces also in Python 3.6...

So it seems to be better to update minimal Python version in `setup.py` to `python_requires= >=3.6` to reflect actual state.

**Comment by isaacharrisholt** [comment]
Updated as of Quiffen v1.2.2
