### ISSUE TITLE
Decimal amount not exact

### ISSUE THREAD

**Issue by paulmcq** [isaacharrisholt/quiffen#18]
In quiffen version 1.2.1 from PyPi, this line in QIF file:
     T-143.66
is translated to:
    amount=Decimal('-143.659999999999996589394868351519107818603515625')

Perhaps issue #5 fix got dropped somewhere???

**Comment by paulmcq** [comment]
I have not understood the code yet, but this code in accounts.py looks problematic:
            elif line_code == 'L':
                kwargs['credit_limit'] = Decimal(round(float(field_info.replace(',', '')), 2))
            elif line_code == '$' or line_code == '£':
                kwargs['balance'] = Decimal(round(float(field_info.replace(',', '')), 2))
field_info is a string, float() converts it to a float, which loses the exactness that we want from Decimal.

**Comment by isaacharrisholt** [comment]
This is a known issue and it's frustrating me to no end. That was an attempt to sort it, but it doesn't seem to have worked.

**Comment by paulmcq** [comment]
I think I have most of it. *All* uses of _float_ are evil.
Let me prepare a patch for you to review...

**Comment by paulmcq** [comment]
I sent you a Pull Request.
It seems to fix the problem in Transactions, at least on my laptop.
Let me know what to do next, because I am a n00b actually working with Git.

However, Loan info is still kept in Float, and I think that should probably
change, too.

**Comment by isaacharrisholt** [comment]
Fixed as of Quiffen v1.2.2
