### ISSUE TITLE
Possible to cope with thousand separators in numbers?

### ISSUE THREAD

**Issue by nzbart** [isaacharrisholt/quiffen#2]
Microsoft Money appears to export values in the local locale, which for me means that large numbers are exported in the form `T25,000.00`. Is it possible to support parsing these values as well as values without thousand separators?

**Comment by isaacharrisholt** [comment]
This support has been added  in version 1.0.1 of Quiffen, which is now available.

**Comment by nzbart** [comment]
Excellent, thanks! Will this be published to pypi.org?

https://pypi.org/project/quiffen/

**Comment by isaacharrisholt** [comment]
Yes it will, however my setup files are on another machine that I don't currently have access to.
