### ISSUE TITLE
Space in header_line keeps account from being identified.

### ISSUE THREAD

**Issue by vampireLibrarianMonk** [isaacharrisholt/quiffen#22]
Could I get the following change so that my account is identifiable?

qif.py line 199            

elif header_line.lower().replace(' ', '') in VALID_TRANSACTION_ACCOUNT_TYPES:

qif.py line 204

accounts[last_account].add_transaction(new_transaction, header_line.replace(' ', ''))

**Comment by isaacharrisholt** [comment]
Hi, this will be added to the backlog, but in future if you're opening an issue with code already written, it'll often be faster to create an issue detailing the problem, then create a pull request with the changes already made.
