### ISSUE TITLE
Importing the library changes the global decimal context

### ISSUE THREAD

**Issue by olivierbellone** [isaacharrisholt/quiffen#24]
`import quiffen` will modify the global `decimal` context ([here](https://github.com/isaacharrisholt/quiffen/blob/v1.2.2/quiffen/__init__.py#L13-L19=)). When using quiffen in an application that also uses `decimal` (or that imports other libraries which themselves use `decimal`), this can lead to incorrect results or even crashes.

Instead, if quiffen really needs this decimal context, it should either pass it manually via the `context` argument when initializing `decimal.Decimal` instances, or use `decimal.localcontext` to create a context manager and run all `decimal` operations in the context manager.

From taking a brief look at the source code, the latter doesn't really seem applicable but the former seems doable. I can take a stab at a PR if you'd like.

**Comment by isaacharrisholt** [comment]
Ah shoot I think I left that in there when testing. My apologies, that's pretty terrible. I think removing the line from the init file should do the trick, and I doubt it'll break any of the tests. I'll see what I can do after work, otherwise yeah feel free to experiment.

**Comment by isaacharrisholt** [comment]
@olivierbellone please check PR #26
