### ISSUE TITLE
Detail Code N

### ISSUE THREAD

**Issue by iamjaymaxx** [isaacharrisholt/quiffen#28]
Hi
Running Quiffen for QIF file "!Type:Oth L" results in various issues.
Using v1.2.0 data with detail code NTransfer, NPrint, etc gives python error ValueError: invalid literal for int() with base 10: 'Transfer'
Updating to v 1.2.4 and the transactions are ignored ie qif.parse returns empty transaction list. Same occurs for Type: 'Oth A' and no error is generated.

My understanding is that Transfer, Print, ATM, etc are valid N-descriptors from Cashbook.  Original Data is
!Type:Oth L
D6/4/21
U370.00
T370.00
NTransfer
PLoan Repayment
LLoan Repayments
^
....
[many lines]
...

In first instance ie v1.2.0, obviously the code is only looking for a numeric Check Number

In 2nd instance, not sure what is happening, as there is nothing in variable acc.transactions (see code below)

Running under PyCharm with Python 3.9 Quiffen 1.2.4 on MacOS 10.13

Basic code is below but the acc.transaction[] keyword is probably incorrect but without the data being read I don't know what it should be to 'Oth L'.  If i change QIF data to !Type:Bank however and use acc.transactions['transaction'] the data is fine as is ie the NTransfer et al details all go through ok.  

from quiffen import Qif
import decimal
if __name__ == '__main__':
    qif = Qif.parse("Current.QIF")

    accts = qif.accounts
    acc = qif.accounts['Quiffen Default Account']
    acc.transactions
    count = 0
    for tr in acc.transactions['Oth L']:    # Yes this is probably wrong keyword
        count += 1
        print(tr)
    print('transaction count: ', count)

My workaround is manually editing !Type to bank is possible but this isn't ideal.  Any other options?

Thanks, appreciate any guidance.

**Comment by isaacharrisholt** [comment]
Hi, apologies for taking so long to get back to you on this. I'm currently working on Quiffen v2, which is a complete overhaul, and will look into fixing this bug as part of that.

**Comment by iamjaymaxx** [comment]
Thx Isaac. Look forward to seeing v2.  

Regards 
James

**Comment by isaacharrisholt** [comment]
Fixed in #36 as part of Quiffen v2
