### ISSUE TITLE
Getting [<class 'decimal.DivisionUndefined'>]

### ISSUE THREAD

**Issue by edwinsantosv** [isaacharrisholt/quiffen#29]
![2022-08-02 005926](https://user-images.githubusercontent.com/66891637/182302681-814acc77-2879-4f09-8756-5ad4a8344be5.png)
as shown, I am getting this error when trying to parse the qif file

**Comment by isaacharrisholt** [comment]
Hi, apologies for taking so long to get back to you on this. I'm currently working on Quiffen v2, which is a complete overhaul, and will look into fixing this bug as part of that.

However, I'm going to need a lot more information. I believe I know the cause of the issue - it's to do with how splits are handled when the transaction value is 0 (see #31 ) - but it would be good to verify this.

**Comment by isaacharrisholt** [comment]
Fixed in #36 as part of Quiffen v2
