### ISSUE TITLE
QIF import fails on !Type:Security

### ISSUE THREAD

**Issue by btownshend** [isaacharrisholt/quiffen#30]
It appears that security lists in the !Type:Security section are not supported.  Subsequent 'T' lines are interpreted as transaction amounts rather than security types.  e.g., here is a QIF fragment:

```
!Type:Security
N
SUSD0000
TStock
GGrowth
^
N
SG002864
TStock
GGrowth
^
N
SM039728
TStock
GGrowth
^
```

**Comment by isaacharrisholt** [comment]
Hi, apologies for taking so long to get back to you on this. I'm currently working on Quiffen v2, which is a complete overhaul, and will look into fixing this bug as part of that.

**Comment by isaacharrisholt** [comment]
Added in #36 as part of Quiffen v2
