### ISSUE TITLE
Zero Total Splits Causing divide by zero err.r

### ISSUE THREAD

**Issue by ukdavewood** [isaacharrisholt/quiffen#31]
Having fun importing some very old Quicken 98 files.  I have found a few split transactions that total to zero.
The Transaction Parser is trying to assign percentages to each split item and getting a divide by zero error.

I have as a workaround written a short pre-processor that finds any zero value split items and adjusts them to be 0.01 - by changing the two total records and adding an additional split transaction.

PS/. Also found that the parser doesn't like GBP £ and I think Euro amounts - as I got a UTF-8 decode error.  So also had to adjust any pound signs or Euro's signs to dollar signs as a workaround too in the same preprocessor

**Comment by isaacharrisholt** [comment]
Hi, apologies for taking so long to get back to you on this. I'm currently working on Quiffen v2, which is a complete overhaul, and will look into fixing this bug as part of that.

**Comment by isaacharrisholt** [comment]
Fixed in #36 as part of Quiffen v2
