### ISSUE TITLE
Child income accounts default to expense

### ISSUE THREAD

**Issue by thehilll** [isaacharrisholt/quiffen#37]
Hello, when using v2.0.0 I'm running into issues parsing this file:

```
!Account
NMy Bank Account
D
TBank
^
!Type:Cat
NParentCat
D
I
^
NParentCat:ChildCat
D
I
^
```

When I try to parse it with:
```python3
from quiffen import Qif
import decimal

qif = Qif.parse('/tmp/test.qif', day_first=False)
for x in qif.categories:
    print(qif.categories[x].name)
    print(qif.categories[x].category_type)
    for child in qif.categories[x].children:
        print(child.name)
        print(child.category_type)
```

The result is:

```
> ./test.py
ParentCat
CategoryType.INCOME
ChildCat
CategoryType.EXPENSE
```

I'm not certain, but I believe the issue comes when the merge happens on line 510 of `category.py`:

```
success = category.merge(root)
```

At this point in the above case the category looks correct (it is an income type):

```
Category:
	Name: ParentCat
	Category Type: income
	Hierarchy: ParentCat
```

However, the representation of the same data in `root` is now incorrect:

```
Category:
	Name: ParentCat
	Category Type: expense
	Hierarchy: ParentCat
	Children: 1
```

it is considered an expense.  I haven't been able to get further than this, but it seems like a category is getting created somewhere with default values (as an expense) and merged over the one that is created with the specified `Income` type.

Thank you very much for this project.

**Comment by isaacharrisholt** [comment]
Thanks for bringing this to my attention. The problem was caused because the temporary category created during category parsing was left as a child of the new category's parent.

A little confusing, but ultimately a simple solution in #38 !

**Comment by thehilll** [comment]
Thank you, this did fix it.
