### ISSUE TITLE
Use decimal values instead of floats to avoid altering values

### ISSUE THREAD

**Issue by nzbart** [isaacharrisholt/quiffen#5]
Floats aren't a great way to represent monetary values because they're inexact. For example, the following number in my .qif file:

> -13769.37

Becomes this value in the Transaction:

> -13769.370000000000800355337560176849365234375

Another example is:

> -2138.20

Which becomes:

> -2138.1999999999998181010596454143524169921875

**Comment by isaacharrisholt** [comment]
Sure, what would you suggest using?

**Comment by isaacharrisholt** [comment]
This is fixed as of version 1.0.2 of Quiffen.

**Comment by nzbart** [comment]
Wow, that was fast!
