### ISSUE TITLE
Is quiffen compatible with pandas 2.x?

### ISSUE THREAD

**Issue by lovette** [isaacharrisholt/quiffen#55]
I'd like to use quiffen on a simple utility I'm writing.

When my requirements.txt pins pandas>2.0.0, the resolver limits me to quiffen 1.2.4.
When my requirements.txt pins quiffen>2.0.0, the resolver limits me to pandas 1.5.3.

I'm running Python version 3.11.3 on macOS.

**Comment by isaacharrisholt** [comment]
I've not tested on pandas 2.x. You should be able to force install it into your environment using something like `pip install --no-deps`. If it works, feel free to submit a PR to adjust the dependency version!

**Comment by lovette** [comment]
I'm generating requirements with `pip-compile`, and it doesn't appear to have a mechanism to let me override or ignore conflicts. I'm on a tight deadline and my project is simple so quiffen 1.2.4 will suffice. The quiffen interface has been easy to work with, thanks!
