### ISSUE TITLE
allow  tqdm progress bar to be used

### ISSUE THREAD

**Issue by WolfgangFahl** [isaacharrisholt/quiffen#75]
the parser might get a progress bar so that the parsing progress may be shown

**Comment by WolfgangFahl** [comment]
works great and is a must have feature for my usecase since the parsing takes some 8 seconds ...

**Comment by isaacharrisholt** [comment]
I don't think this is a necessary feature for most users, and it's something extra I would have to keep maintained. Will not implement at this time.
