### ISSUE TITLE
Does not parse QIF files with commas in T fields

### ISSUE THREAD

**Issue by ChristineTham** [isaacharrisholt/quiffen#8]
Example transaction (exported from Banktivity)
```
^
D16/5/17
T-1,513.33
Cc
PIcare
MANZ INTERNET BANKING BPAY ICARE WORKERS INS
LInsurance
```

**Comment by isaacharrisholt** [comment]
This has already been fixed as of issue #2. See this commit for details:
https://github.com/isaacharrisholt/quiffen/commit/394a42357af37a1e3fa34e7844a5bea435e2065d
